[project]
name = "rix-dsl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Eric Nantz", email = "theRcast@gmail.com" }
]
requires-python = ">=3.13.5"
dependencies = [
    "great-docs>=0.16.0",
]

[project.scripts]
rix-dsl = "rix_dsl:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
great-docs = { git = "https://github.com/posit-dev/great-docs" }
